# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: 'Run Pester tests'
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Install-Module Pester -Force -Verbose
      Import-Module Pester -Force -Verbose
      Invoke-Pester test/nexus.Tests.ps1
    failOnStderr: true
    pwsh: true
