# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: 'Run Pester tests'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module Pester -Force
      Import-Module Pester -Force
      $result = Invoke-Pester -CodeCoverage ./ -Show None -PassThru
      if($result.FailedCount -gt 0) {
        $result.TestResult | Where-Object {$_.Result -ne "Passed"}
        Exit 1
      }
      else {
        write-output $result.TestResult
      }
      write-output "`n`n----------------Missed Commands----------------`n"
      write-output $result.CodeCoverage.MissedCommands
      write-output "`n----------------Missed Commands----------------`n`n`n"
      $coverage = $(100*$($result.CodeCoverage.NumberOfCommandsExecuted)/$($result.CodeCoverage.NumberOfCommandsAnalyzed))
      write-host "Code coverage :  % $coverage"
      if($coverage -lt 40) {
          Write-Host "Code coverage should be minimum %40"
          Exit 1
      }
    failOnStderr: true
    pwsh: true
